modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/CraftTweaker/CraftTweaker/issues"
[[mods]]
modId="crafttweaker"
version="${file.jarVersion}"
displayName="CraftTweaker"
displayURL="https://minecraft.curseforge.com/projects/crafttweaker"
updateJSONURL="https://updates.blamejared.com/get?n=crafttweaker&gv=1.15.2"
logoFile="logo.png"
authors="Jaredlll08, Kindlich and StanH"
description="Customize your minecraft experience!"
[[dependencies.crafttweaker]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.crafttweaker]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"