modLoader="javafml"
loaderVersion="[34,)"
issueTrackerURL="https://github.com/CraftTweaker/CraftTweaker/issues"
license="MIT"
[[mods]]
modId="crafttweaker"
version="${file.jarVersion}"
displayName="CraftTweaker"
displayURL="https://minecraft.curseforge.com/projects/crafttweaker"
updateJSONURL="https://updates.blamejared.com/get?n=crafttweaker&gv=1.16.3"
logoFile="logo.png"
authors="Jaredlll08, Kindlich and StanH"
description="Customize your minecraft experience!"